### ISSUE TITLE
Add topic validation before publishing

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-mqtt-client#11]
Add topic validation before publishing (i.e. can't contain wildcards, the # can be only at the end, max topic length, the + can be used only between /, ...)

**Comment by Sammers21** [comment]
I have read the spec and here is what I found:
```
[MQTT-3.3.2-2] | The Topic Name in the PUBLISH Packet MUST NOT contain wildcard characters.
```
And I can't find the information that we might have # wildcard at the end of topic. 

Can you point me out?

**Comment by ppatierno** [comment]
See section : 

4.7.1.2 Multi-level wildcard

4.7.1.3 Single level wildcard

**Comment by Sammers21** [comment]
When we publish something, the PUBLISH packet has Topic Name.
When we subscribe for some topics we use Topic Filters.

According to what I see, we can't use # char at the end of Topic Name when publishing. But, it MUST be the last character in the Topic Filter when subscribing.

Correct me if I'm wrong.

**Comment by ppatierno** [comment]
When you publish you have to pass a specific topic so no wildcards (+ or #).
When you subscribe you can subscribe to a specific topic or you can using filters which means using even wildcards. 
For example :  

a subscriber can subscribe to /foo/a/b (specific topic) or /foo/# (so getting messages published on /foo/a/b or /foo/c) or /foo/+/b (so getting messages from /foo/a/b or /foo/A/b).
the publisher has to publish always on a specific topic. It can't publish on /foo/# or /foo/+/b.
