### ISSUE TITLE
Using the new Vert.x net client

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-mqtt-client#12]
Moving to use the new Vert.x net client for extending it and building the MQTT client. A reference could be the MQTT server as well, which has a PR (https://github.com/vert-x3/vertx-mqtt-server/pull/29) for moving to the new net server.
@Sammers21 I'd like that you work on that as primary effort. Is it ok for you ?

**Comment by Sammers21** [comment]
Sure, it's ok

**Comment by Sammers21** [comment]
Should be closed? right?

**Comment by ppatierno** [comment]
Yes ;)
