### ISSUE TITLE
some CI system?

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt-client#2]
What do you think about some CI system like travis or circle?

**Comment by alexlehm** [comment]
Vert.x uses a Jenkins service hosted by Cloudbees at https://vertx.ci.cloudbees.com/, Julien can give you access if you create an account I think.

**Comment by ppatierno** [comment]
Yes I think that @vietj can set up it for us as he already did for the MQTT server component.

**Comment by vietj** [comment]
absolutely

**Comment by vietj** [comment]
I'm going to setup a CI on the initial-work branch

**Comment by vietj** [comment]
https://vertx.ci.cloudbees.com/job/vert.x3-mqtt-client/

**Comment by ppatierno** [comment]
Thanks @vietj !
