### ISSUE TITLE
MQTT broker for testing

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt-client#3]
vertx-mqtt-server currently used for testing in my forked repository, but ... it's not a broker. The thing that will make testing more convenient and fast is a usage of a "full broker". 

Are there any suggestions what should be used for testing purposes?

I have noticed at least two candidates that could be used for testing purposes:

- https://github.com/andsel/moquette
- https://github.com/GruppoFilippetti/vertx-mqtt-broker

**Comment by ppatierno** [comment]
I have never used this MQTT broker before and using one of them we have the advantage to use always Java stuff. Maybe the better MQTT compliant and well tested broker to use could be Mosquitto (but it's in C) which is not embeddable in out unit tests. @vietj wdyt ? There is some other Vert.x project which need an external component for testing if I'd like to use Mosquitto for testing the MQTT client ?

**Comment by ppatierno** [comment]
@Sammers21 waiting for this decision, have you already tried to write a simple example using this library for interacting with Mosquitto for example ? I mean to create a new repo on your personal GitHub account and not inside the MQTT client project. Just to see how does the interaction work :-)

**Comment by Sammers21** [comment]
@ppatierno , No, I haven't. But, i could try.

**Comment by vietj** [comment]
doesn't have mqtt a kind of TCK ?

**Comment by vietj** [comment]
what is Paho actually using ?

**Comment by Sammers21** [comment]
@vietj , I'm not sure, but i could assume that they use an remote broker located here: tcp://iot.eclipse.org:1883

This assumption made after running this test: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3.test/src/test/java/org/eclipse/paho/client/mqttv3/test/SendReceiveTest.java#L188

 And the output is:
![image](https://user-images.githubusercontent.com/16746106/27011546-694840b0-4ec6-11e7-86a3-252f3499dbe6.png)

**Comment by ppatierno** [comment]
@Sammers21 it seems that you are right because in the `setUpBeforeClass` there is the following line : 

`
serverURI = TestProperties.getServerURI();
`

where the `TestProperties` class reads information from the following properties file.

https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3.test/src/test/resources/test.properties

**Comment by ppatierno** [comment]
And they use Mosquitto as broker listening on that address.

**Comment by vietj** [comment]
can we run the `io.eclipse.org:1883` locally ?

**Comment by ppatierno** [comment]
@vietj it's exactly what I was asking. How it works for other Vert.x projects which can need to start something locally for unit testing ? We could use Mosquitto locally that is used for the `io.eclipse.org:1883`.

**Comment by vietj** [comment]
is mosquitto embeddable in unit tests ?

**Comment by ppatierno** [comment]
Mosquitto isn't embeddable (i.e. it's not like having Debezium which provides you a Kafka cluster to start in your code). Mosquitto is developed in C; we should start it as an external process from the Java code.

**Comment by vietj** [comment]
can we use a docker image ?

**Comment by ppatierno** [comment]
I'm fine with that because we already use Docker images in the EnMasse project for some tests in Travis CI.

**Comment by Sammers21** [comment]
@ppatierno , sorry for delay.

I have created repository for testing with Docker: https://github.com/Sammers21/Mosquitto_junit_testing

It uses ansi/mosquitto docker image and runs new docker container before each test and removes after.

Also, I have set up Travis CI to make sure all works fine.

**Comment by ppatierno** [comment]
@Sammers21 I took a look at the repository. The idea is good but I would use the fabric8 Docker Maven plugin for that. With your code you need to start the Docker container from code using `ProcessBuilder` and some script. With the fabric8 plugin in you can configure Maven for getting the image when running integration tests. You can take a look here : 

https://github.com/eclipse/hono/blob/master/tests/pom.xml

This is the way as Eclipse Hono run some containers for integration tests.

**Comment by Sammers21** [comment]
@ppatierno , could you check it one more time? Is it ok now?

**Comment by ppatierno** [comment]
@Sammers21 checked and you have already updated the PR. I'm going to close this issue.
